apiVersion: k3d.io/v1alpha3
kind: Simple
name: devspace-base
servers: 1
agents: 1
kubeAPI:
  hostPort: "6550"
image: rancher/k3s:v1.20.12-k3s1
registries:
  use:
    - registry.k3d.localhost:5000
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
